### ISSUE TITLE
Github Actions yml 파일 추가

### ISSUE THREAD

**Issue by minhyeok0328** [minhyeok0328/next-loop#10]
- [ ] 각 폴더 별로 (/airflow, /backend 등) commit 되면 감지해서 각각 다른 인스턴스에 자동배포 되게 파일 추가
- [ ] pull requests 남길 때 어떻게 동작하는지 설명 추가

**Comment by dnlpys** [comment]
메인에 pr되면 인스턴스 접속해서 코드 업데이트 해주는 구조인가요?

**Comment by minhyeok0328** [comment]
네 맞습니다 그렇게 하려구요
airflow/
backend/
...

이렇게 폴더별로 변경사항 감지해서 배포 가능해서 그렇게 하면 좋을 것 같아서요
사실상 main이 develop 브랜치여서 main에 pr되면 배포되게 해주면 될 것 같습니당
