### ISSUE TITLE
MLFlow 세팅

### ISSUE THREAD

**Issue by minhyeok0328** [minhyeok0328/next-loop#16]
- [x] MLFLow docker image 사용해서 세팅
- [x] 간단하게 pytorch 모델 만들어서(GPT가 잘 만들어 줍니다) 학습까지 잘 되는지 테스트

**Comment by SOONSOO7** [comment]
local에서 docker image 사용 세팅, 간단하게 pytorch 모델 만들어서 학습 완료 테스트 완료

**Comment by SOONSOO7** [comment]
<img width="956" alt="20241030_141631" src="https://github.com/user-attachments/assets/78946e5c-7fc3-47a4-9224-aeb8a47af619">

**Comment by SOONSOO7** [comment]
<img width="925" alt="20241030_141857" src="https://github.com/user-attachments/assets/8b7462f3-96d1-46a8-a72a-d75019005c1a">
<img width="956" alt="20241030_141848" src="https://github.com/user-attachments/assets/0a2f112c-009f-44cb-89ec-0649b3cf35a4">
<img width="953" alt="20241030_141831" src="https://github.com/user-attachments/assets/dd9aadae-7f44-448c-b614-a6659969ffaa">

**Comment by SOONSOO7** [comment]
- [] s

**Comment by SOONSOO7** [comment]
- [ ] local에서 git push - branch : mlflow-pytorch-1
- [ ] mlflow 인스턴스 구축
- [ ] 인스턴스에서 git pull
- [ ] gcp instance 환경에서 구축
- [ ] 인스턴스에서 git push
- [ ] github git pull & request

**Comment by SOONSOO7** [comment]
<img width="940" alt="20241031_182308" src="https://github.com/user-attachments/assets/5bf97597-d1f4-4b9d-9b14-6119b7314663">
<img width="960" alt="20241031_180822" src="https://github.com/user-attachments/assets/701cf92d-333b-467c-b05d-40c82ee53613">
<img width="960" alt="20241031_180813" src="https://github.com/user-attachments/assets/d684ab3d-e777-4964-be51-5d3383497c82">
<img width="960" alt="20241031_180407" src="https://github.com/user-attachments/assets/f41cb081-1654-4c85-8600-d17d53353a24">
<img width="940" alt="20241031_180358" src="https://github.com/user-attachments/assets/f652582c-3831-4e3c-bd31-bdf56fe9d370">

**Comment by SOONSOO7** [comment]
- [ ] MLFlow에 인스턴스 사양을 기본으로 했는데, MLFlow 등 모델 학습 인스턴스는 Deep Learning VM with CUDA 12.3 M125(https://www.notion.so/12ae900739a3817c8316fc9742e72ffa?v=12ae900739a381f7b208000c6d445438&p=047ae59584cb44539d14a95010529dee&pm=s)에 따라 향후 개발시 새로운 인스턴스를 생성해야 할 것 같습니다.
