### ISSUE TITLE
Airflow 배포

### ISSUE THREAD

**Issue by minhyeok0328** [minhyeok0328/next-loop#2]
- [x] Airflow 배포 후에 url 팀원들에게 공유하기

**Comment by SOONSOO7** [comment]
cli로 gcp 접속 완료

**Comment by SOONSOO7** [comment]
VM 인스턴스 생성 완료

**Comment by SOONSOO7** [comment]
다른 팀원 접속 완료

**Comment by SOONSOO7** [comment]
airflow unhealthy 확인

**Comment by SOONSOO7** [comment]
logs 확인 결과 정상작동중. unhealthy로 표기되는 것은 healthcheck설정 때문일 수 있음

**Comment by SOONSOO7** [comment]
인스턴스에서 배포한 에어플로우를 test-pipes branch에 commit 하고 pull request함.
